<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/7
 * Time: 9:44
 */
//创建一个模块类，用来帮模块内代码共享数据和组件
namespace app\modules\forum;
class Module extends \yii\base\Module
{
    //定义一个初始化函数
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->params['foo']='bar';
//        \Yii::configure($this, require(__DIR__ . '/config.php')); //可以在配置文件 config.php 中配置好一些初始化的代码，然后直接调用即可
        $this->modules = [
//            模块嵌套
            'admin' =>[
                'class' => 'app\modules\forum\admin\Module',
            ],
        ];
    }
}